---

- name: git checkout anmad
  git:
    repo: https://github.com/jefg60/anmad.git
    dest: "{{ anmad.install_dir }}"
    clone: yes
    version: 0.21.2
  tags: anmad
  notify:
    - restart anmad

- name: install anmad module with pip
  pip:
    name:
      # forked ansible-vault to apply patches for ansible 2.10
      - git+https://github.com/jefg60/ansible-vault.git
      - "{{ anmad.install_dir }}"
    virtualenv: "{{ ansible_master.venv }}"
    virtualenv_site_packages: true
    state: present

- name: deploy ssh-askpass script
  template:
    src: ssh-askpass.j2
    dest: /usr/bin/ssh-askpass
    owner: root
    group: "{{ ansible_master.group }}"
    mode: 0750
  when: master_ansible_user_vaultfile is defined
  tags: anmad

- name: deploy anmad config file
  template:
    src: anmad.conf.j2
    dest: "/etc/anmad.conf"
    mode: 0644
    owner: root
    group: root
  tags: anmad
  notify:
    - reload anmad

- name: deploy anmad rsyslog conf
  copy:
    src: anmad-rsyslog.conf
    dest: /etc/rsyslog.d/
    mode: 0644
    owner: root
    group: root
  tags: anmad
  notify:
    - restart rsyslog

- name: deploy anmad .service files
  copy:
    src: "anmad.service"
    dest: /etc/systemd/system/
    mode: 0644
    owner: root
    group: root
  tags: anmad
  notify:
    - systemctl daemon-reload
    - restart anmad

- name: ensure anmad systemd services are running
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    masked: false
  loop:
    - anmad
    - redis

- name: create /etc/htpasswd folder
  file:
    path: /etc/htpasswd
    state: directory
    owner: root
    group: root
    mode: 0755

# command is used here because htpasswd module doesnt work with bcrypt
- name: Create admin user in htpasswd file with bcrypt
  command: "htpasswd -b -c -B -C 11 /etc/htpasswd/.htpasswd \
    {{ anmad.interface.username }} {{ anmad.interface.password }}"
  changed_when: false
  no_log: true
