---
- name: install packages, set up git and anmad
  include: "{{ include_item }}"
  with_items:
    - packages.yaml
    - ansible-user.yaml
    - git.yaml
    - ssl.yaml
    - anmad.yaml
    - gunicorn.yaml
    - nginx.yaml
  loop_control:
    loop_var: include_item

- name: create /var/log/ansible
  file:
    path: /var/log/ansible
    state: directory
    owner: "{{ ansible_master.user }}"
    group: git
    mode: 0755

- name: create roles dir
  file:
    name: /etc/ansible/roles
    owner: "{{ ansible_master.user }}"
    state: directory
    mode: 0755

- name: create sensitive log dirs
  file:
    path: "/var/log/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_master.user }}"
    group: "{{ ansible_master.group }}"
  loop:
    - 'ansible/playbook'
    - 'anmad'

- name: deploy rsyslog.conf #https://askubuntu.com/questions/1066997/every-few-minutes-rsyslog-outputs-rsyslogd-action-action-3-resumed-module)
  copy:
    src: rsyslog.conf
    dest: /etc/

- name: put virtualhosts into hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.0.1 {{ item }}"
    line: "127.0.0.1 {{ item }}"
  loop:
    - "{{ anmad.host }}"

- name: Ensure Nginx server is started
  become: true
  systemd:
    state: started
    name: nginx
    enabled: true

- name: flush handlers before doing tests
  meta: flush_handlers

- name: TEST anmad homepage is up - external https server
  uri:
    url: "https://{{ anmad.host }}:{{ anmad.port }}/"
    user: "{{ anmad.interface.username }}"
    password: "{{ anmad.interface.password }}"
    validate_certs: false
    return_content: yes
  register: anmad_page
  failed_when: "'run all (green) playbooks' not in anmad_page.content"
  tags:
    - tests

- name: start ara container
  community.general.docker_container:
    name: ara
    image: recordsansible/ara-api:latest
    state: started
    detatch: true
    tty: true
    volumes:
      - ~/.ara/server:/opt/ara:z
    ports:
     - "8000:8000"
