---
- name: install packages, set up git and anmad
  include: "{{ include_item }}"
  with_items:
    - packages.yaml
    - ansible-user.yaml
    - git.yaml
    - ssl.yaml
    - anmad.yaml
  loop_control:
    loop_var: include_item

- name: create /var/log/ansible
  file:
    path: /var/log/ansible
    state: directory
    owner: "{{ ansible_orchestration_user }}"
    group: git
    mode: 0755

- name: create roles dir
  file:
    name: /etc/ansible/roles
    owner: "{{ ansible_orchestration_user }}"
    state: directory
    mode: 0755

- name: create ansible playbook log dir
  file:
    path: /var/log/ansible/playbook
    state: directory
    mode: 0755
    owner: "{{ ansible_orchestration_user }}"
    group: "{{ ansible_orchestration_group }}"

- name: put virtualhosts into hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.0.1 {{ item }}"
    line: "127.0.0.1 {{ item }}"
  loop:
    - "{{ anmad_host }}"

- name: Ensure Nginx server is started
  become: true
  systemd:
    state: started
    name: nginx
    enabled: true

- name: flush handlers before doing tests
  meta: flush_handlers

- name: TEST anmad homepage is up - external https server
  uri:
    url: "https://{{ anmad_host }}:{{ anmad_port }}/"
    user: "{{ anmad_control_username }}"
    password: "{{ anmad_control_password }}"
    validate_certs: false
    return_content: yes
  register: anmad_page
  failed_when: "'run all (green) playbooks' not in anmad_page.content"
  tags:
    - tests
