---
- name: install packages, set up git and anmad
  include: "{{ include_item }}"
  with_items:
    - packages.yaml
    - ansible-user.yaml
    - git.yaml
    - ssl.yaml
    - anmad.yaml
  loop_control:
    loop_var: include_item

- name: create /var/log/ansible
  file:
    path: /var/log/ansible
    state: directory
    owner: "{{ ansible_orchestration_user }}"
    group: git
    mode: 0755

- name: create roles dir
  file:
    name: /etc/ansible/roles
    owner: "{{ ansible_orchestration_user }}"
    state: directory
    mode: 0755

- name: symlink /etc/ara/ara.cfg as /etc/ansible/ansible.cfg
  file:
    src: /etc/ara/ara.cfg
    dest: /etc/ansible/ansible.cfg
    state: link
    force: true
  when: link_ansible_cfg

- name: put apache virtualhosts into hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.0.1 {{ item }}"
    line: "127.0.0.1 {{ item }}"
  loop:
    - "{{ anmad_host }}"
    - "{{ ara.config.host }}"

- name: remove ansible logging opt from ansible/ara.cfg
  # (its now done by an env var in the subprocess called by anmad)
  ini_file:
    dest: /etc/ara/ara.cfg
    section: defaults
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: absent
  with_items:
    - { option: log_path, value: /var/log/ansible/ansible.log }

- name: Ensure Apache server is started
  become: true
  systemd:
    state: started
    name: apache2
    enabled: true

- name: flush handlers before doing tests
  meta: flush_handlers

- name: wait for ara service port
  wait_for:
    port: "{{ ara.config.port }}"
    host: "{{ ara.config.host }}"
  when: ara.deployment.server == 'embedded'

- name: TEST ara homepage is up - external https server
  uri:
    url: "https://{{ ara.config.host }}:{{ ara.config.port_ssl }}/about/"
    user: "{{ anmad_control_username }}"
    password: "{{ anmad_control_password }}"
    validate_certs: false
    return_content: yes
  register: ara_aboutpage
  when: ara.deployment.server != 'embedded'
  failed_when: "'ARA Records Ansible' not in ara_aboutpage.content"

- name: debug ara_aboutpage var
  debug:
    var: ara_aboutpage
    verbosity: 1

- name: TEST ara homepage is up - embdedded server
  uri:
    url: "http://{{ ara.config.host }}:{{ ara.config.port }}/about/"
    return_content: yes
  register: ara_aboutpage
  when: ara.deployment.server == 'embedded'
  failed_when: "'ARA Records Ansible' not in ara_aboutpage.content"

- name: debug ara_aboutpage var
  debug:
    var: ara_aboutpage
    verbosity: 1

- name: TEST anmad homepage is up - external https server
  uri:
    url: "https://{{ anmad_host }}:{{ anmad_port }}/"
    user: "{{ anmad_control_username }}"
    password: "{{ anmad_control_password }}"
    validate_certs: false
    return_content: yes
  register: anmad_page
  failed_when: "'run all (green) playbooks' not in anmad_page.content"
