---
- name: install packages, set up git
  include: "{{ include_item }}"
  with_items:
    - packages.yaml
    - ansible-user.yaml
    - git.yaml
  loop_control:
    loop_var: include_item

- name: create /var/log/ansible
  file:
    path: /var/log/ansible
    state: directory
    owner: "{{ ansible_orchestration_user }}"
    group: git
    mode: 0755

- name: create roles dir
  file:
    name: /etc/ansible/roles
    owner: "{{ ansible_orchestration_user }}"
    state: directory
    mode: 0755

- name: deploy ansible-runner.py
  copy:
    src: ansible-runner.py
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  tags: runner

- name: deploy ansible-runner-screen.sh
  template:
    src: ansible-runner-screen.sh.j2
    dest: /usr/local/bin/ansible-runner-screen.sh
    mode: 0755
    owner: root
    group: root
  tags: runner

- name: check for existing screens
  command: screen -ls ansible-runner
  register: runningscreens
  tags: runner
  become: true
  become_user: "{{ ansible_orchestration_user }}"
  ignore_errors: yes
  changed_when: false

- name: start a new ansible-runner screen
  command: /usr/local/bin/ansible-runner-screen.sh
  when: runningscreens.failed and start_ansible_runner_in_screen
  become: true
  become_user: "{{ ansible_orchestration_user }}"
