#ansible-master role
---
become: yes
tasks:
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - openssh-server
  - git
  - ansible
  - python-dns
  - python-txwinrm
  - ansible-lint
  - python-apt
  - python-pip

- name: install python pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - pywinrm
    - dnspython

- name: create git user
  user:
    name: "{{ git_username }}"
    shell: /usr/bin/false
    home: "{{ git_homedir }}"

- name: deploy key to git user
  authorized_key:
    user: "{{ git_username }}"
    state: present
    key: "https://github.com/{{ github_username }}.keys"

- name: create git repo
  command: "git init --bare {{ git_homedir }}/{{ git_repo_name }}.git"
  args:
    creates: "{{ git_homedir }}/{{ git_repo_name }}.git/HEAD"
  become_user: git

- name: clone git repo to run dir
  git:
    repo: "{{ git_homedir }}/{{ git_repo_name }}.git"
    dest: "{{ git_repo_target }}"

- name: post-update git hook which pulls from run dir after each push
  copy:
    dest: "{{ git_homedir }}/{{ git_repo_name }}.git/hooks/post-update"
    content: "cd {{ git_repo_target }} ; git pull"

- name: create roles dir
  file:
    name: /etc/ansible/roles
    owner: root
    state: directory
    mode: 0755
