---
- name: install packages, set up git
  include: "{{ include_item }}"
  with_items:
    - packages.yaml
    - ansible-user.yaml
    - git.yaml
  loop_control:
    loop_var: include_item

- name: create /var/log/ansible
  file:
    path: /var/log/ansible
    state: directory
    owner: "{{ ansible_orchestration_user }}"
    group: git
    mode: 0755

- name: create roles dir
  file:
    name: /etc/ansible/roles
    owner: "{{ ansible_orchestration_user }}"
    state: directory
    mode: 0755

- name: git checkout ansible-logpoll
  git:
    repo: https://github.com/jefg60/ansible-logpoll.git
    dest: /srv/ansible-logpoll
    clone: yes
    version: 0.8.1
  tags: logpoll

- name: symlink ansible_logpoll.py
  file:
    src: /srv/ansible-logpoll/ansible_logpoll.py
    dest: /usr/local/bin/ansible-logpoll.py
    force: yes
    owner: root
    group: root
    state: link
  tags: logpoll

- name: deploy ansible-logpoll-screen.sh
  template:
    src: ansible-logpoll-screen.sh.j2
    dest: /usr/local/bin/ansible-logpoll-screen.sh
    mode: 0755
    owner: root
    group: root
  tags: logpoll

- name: symlink /etc/ara/ara.cfg as /etc/ansible/ansible.cfg
  file:
    src: /etc/ara/ara.cfg
    dest: /etc/ansible/ansible.cfg
    state: link
    force: true
  when: link_ansible_cfg

- name: check for existing screens
  command: screen -ls ansible-logpoll
  register: runningscreens
  tags: logpoll
  become: true
  become_user: "{{ ansible_orchestration_user }}"
  ignore_errors: yes
  changed_when: false

- name: start a new ansible-logpoll screen
  command: /usr/local/bin/ansible-logpoll-screen.sh
  when: runningscreens.failed and start_ansible_logpoll_in_screen
  become: true
  become_user: "{{ ansible_orchestration_user }}"
  tags: logpoll

- name: flush handlers before doing tests
  meta: flush_handlers

- name: wait for ara service port
  wait_for:
    port: "{{ ara.config.port }}"
    host: "{{ ara.config.host }}"
  when: ara.deployment.server == 'embedded'

- name: TEST ara homepage is up - external http server
  uri:
    url: "http://{{ ara.config.host }}/about/"
    return_content: yes
  register: ara_aboutpage
  when: ara.deployment.server != 'embedded'
  failed_when: "'ARA Records Ansible' not in ara_aboutpage.content"

- name: debug ara_aboutpage var
  debug:
    var: ara_aboutpage
    verbosity: 1

- name: TEST ara homepage is up - embdedded server
  uri:
    url: "http://{{ ara.config.host }}:{{ ara.config.port }}/about/"
    return_content: yes
  register: ara_aboutpage
  when: ara.deployment.server == 'embedded'
  failed_when: "'ARA Records Ansible' not in ara_aboutpage.content"

- name: debug ara_aboutpage var
  debug:
    var: ara_aboutpage
    verbosity: 1
