---
- name: deploy anmad nginx conf
  template:
    src: anmad-nginx.conf
    dest: "/etc/nginx/sites-available/{{ anmad.host }}.conf"
  notify: reload nginx

- name: remove nginx default symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: symlink anmad site conf to sites-enabled
  file:
    src: "/etc/nginx/sites-available/{{ anmad.host }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ anmad.host }}.conf"
    state: link
  notify: reload nginx

# command is used here because htpasswd module doesnt work with bcrypt
- name: Create admin user in htpasswd file with bcrypt
  command: "htpasswd -b -c -B -C 11 /etc/htpasswd/.htpasswd-{{ anmad.host }} \
    {{ anmad_credentials.username }} {{ anmad_credentials.password }}"
  changed_when: false
  no_log: true
