---
- name: add vagrant repo key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
    state: present

- name: add vagrant repo
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    state: present
    update_cache: no

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - openssh-server
  - git
  - ansible
  - python-dns
  - python-txwinrm
  - ansible-lint
  - python-apt
  - python-pip
  - python3-pip
  - vagrant

- name: install python pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - pywinrm
    - dnspython

# may or may not be required, depends if my ansible-runner.py is used
- name: install pip3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - ssh-agent-setup
    - watchdog3
