---
- name: install OS packages
  apt:
    name:
      - openssh-server
      - git
      - python3-pip
      - python3-apt
      - redis
      - python3-passlib
      - python3-virtualenv
      - apache2-utils
      - nginx
      - acl
    state: latest
    update_cache: yes

- name: install pip packages to virtualenv
  pip:
    name:
      - 'ansible<2.10'
      - ansible-lint
      - pywinrm
      - dnspython
      - gunicorn
    virtualenv: "{{ ansible_master.venv }}"
    virtualenv_site_packages: true
    state: present
