---
- name: add vagrant repo key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
    state: present

- name: add vagrant repo
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    state: present
    update_cache: no

- name: add ansible repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
    state: present

- name: add ansible repo
  apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main
    state: present
    update_cache: no

- name: install packages
  apt:
    name:
      - openssh-server
      - git
      - python-dns
      - python-txwinrm
      - ansible-lint
      - python-apt
      - python-pip
      - python3-pip
      - vagrant
    state: present
    update_cache: yes

- name: install ansible
  apt:
    name: 'ansible={{ ansible_install_version }}'
    state: latest

- name: install python pip packages
  pip:
    name:
      - pywinrm
      - dnspython

# required for ansible-runner.py
- name: install pip3 packages
  pip:
    name:
      - ssh-agent-setup
      - watchdog3
    executable: pip3
