---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - openssh-server
  - git
  - ansible
  - python-dns
  - python-txwinrm
  - ansible-lint
  - python-apt
  - python-pip
  - python3-pip

- name: install python pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - pywinrm
    - dnspython

# may or may not be required, depends if my ansible-runner.py is used
- name: install pip3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - ssh-agent-setup
