---
- name: add ansible repo key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 93C4A3FD7BB9C367
    state: present

- name: add ansible repo
  apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main
    state: present
    update_cache: no

- name: install OS packages
  apt:
    name:
      - openssh-server
      - git
      - python3-pip
      - python3-apt
      - redis
      - python3-passlib
      - python3-virtualenv
      - apache2
      - apache2-dev
    state: latest
    update_cache: yes

- name: install pip packages to virtualenv
  pip:
    name:
      - ansible-lint
      #- ansible-vault # this is bundled with anmad in the ansible-2.10 branch
      - ansible
      - pywinrm
      - dnspython
      - ssh-agent-setup
      - configargparse
      - flask
      - hotqueue
      - redis
      - cryptography>=3.1.1
      - psutil
      - mod_wsgi
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_site_packages: true
    state: present
