---
- name: add vagrant repo key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
    state: present

- name: add vagrant repo
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    state: present
    update_cache: no

- name: add ansible repo key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 93C4A3FD7BB9C367
    state: present

- name: add ansible repo
  apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main
    state: present
    update_cache: no

- name: install OS packages
  apt:
    name:
      - openssh-server
      - git
      - python3-pip
      - vagrant
      - sqlite3
      - python3-apt
      - redis
      - python3-passlib
    state: latest
    update_cache: yes

- name: install pip packages to virtualenv
  pip:
    name:
      - ansible-lint
      - ansible-vault
      - ansible
      - pywinrm
      - dnspython
      - ssh-agent-setup
      - configargparse
      - flask
      - hotqueue
      - redis
      - cryptography
      - psutil
    virtualenv: "{{ ara_override.install.pip.virtualenv_path }}"
    virtualenv_python: python3.7
    virtualenv_site_packages: true
    state: latest

- name: deploy ansible-playbook-wrapper script (log per playbook)
  template:
    src: ansible-playbook-wrapper.j2
    dest: "{{ ara_override.install.pip.virtualenv_path }}/bin/ansible-playbook-wrapper"
    owner: ansible
    group: users
    mode: 0770
