---
- name: Ensure directory exists for TLS certs.
  file:
    path: "{{ ansible_master.ssl_cert_dir }}/{{ item }}"
    state: directory
  loop:
    - "{{ anmad.host }}"

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{ ansible_master.ssl_cert_dir }}/{{ item }}/privkey.pem"
  loop:
    - "{{ anmad.host }}"
  when: ansible_master.ssl_cert_dir == "/etc/letsencrypt/selfsigned"

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "/etc/ssl/private/{{ item }}.csr"
    privatekey_path: "{{ ansible_master.ssl_cert_dir }}/{{ item }}/privkey.pem"
    common_name: "{{ item }}"
  loop:
    - "{{ anmad.host }}"
  when: ansible_master.ssl_cert_dir == "/etc/letsencrypt/selfsigned"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: "{{ ansible_master.ssl_cert_dir }}/{{ item }}/fullchain.pem"
    privatekey_path: "{{ ansible_master.ssl_cert_dir }}/{{ item }}/privkey.pem"
    csr_path: "/etc/ssl/private/{{ item }}.csr"
    provider: selfsigned
  loop:
    - "{{ anmad.host }}"
  when: ansible_master.ssl_cert_dir == "/etc/letsencrypt/selfsigned"
