---
# handlers file for ansible-master
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart anmad_dirpoll
  service:
    name: anmad_dirpoll
    state: restarted

- name: restart anmad_buttons
  service:
    name: anmad_buttons
    state: restarted

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
