---
# handlers file for ansible-master
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart anmad
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - anmad
    - anmad-gunicorn

- name: reload anmad
  service:
    name: "{{ item }}"
    state: reloaded
  loop:
    - anmad
    - anmad-gunicorn
  ignore_errors: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload gunicorn
  service:
    name: gunicorn.socket
    state: reloaded
