---
# handlers file for ansible-master
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart anmad
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - "anmad-{{ anmad.host }}"
    - "anmad-{{ anmad.host }}-gunicorn"

- name: reload anmad
  service:
    name: "{{ item }}"
    state: reloaded
  loop:
    - "anmad-{{ anmad.host }}"
    - "anmad-{{ anmad.host }}-gunicorn"
  ignore_errors: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload gunicorn
  service:
    name: "anmad-{{ anmad.host }}-gunicorn.socket"
    state: reloaded
