---
# handlers file for ansible-master
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart anmad_dirpoll
  service:
    name: anmad_dirpoll
    state: restarted

- name: restart anmad_buttons
  service:
    name: anmad_buttons
    state: restarted

- name: restart anmad
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - anmad_dirpoll
    - anmad_buttons
    - anmad_run

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
