---
# handlers file for ansible-master
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart anmad
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - anmad_run

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: reload apache
  service:
    name: apache2
    state: reloaded
