---
# handlers file for ansible-master
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart anmad_dirpoll
  service:
    name: anmad_dirpoll
    state: restarted

- name: restart anmad
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - anmad_dirpoll
    - anmad_run
    - apache2

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: reload apache
  service:
    name: apache2
    state: reloaded
