---
# handlers file for ansible-master
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart ansible-logpoll
  service:
    name: ansible-logpoll
    state: restarted

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
