---
- hosts: ansible_master
  tasks:
    - name: clone bats from github
      git:
        repo: https://github.com/sstephenson/bats.git
        dest: /tmp/bats

    - name: install bats
      shell: "./install.sh /usr/local"
      args:
        chdir: /tmp/bats
        creates: /usr/local/bin/bats
      become: yes

    - name: create testdata dir and results dir
      file:
        path: "{{ item }}"
        state: directory
      become: no
      with_items:
        - /home/vagrant/testdata
        - /vagrant/tests/results

    - name: create testdata file
      copy:
        content: "git test success"
        dest: /home/vagrant/testdata/testfile
      become: no

    - name: copy deploy*.yaml to testdata dir
      copy:
        src: "{{ item }}"
        dest: /home/vagrant/testdata/ansible/
        mode: 0664
      with_fileglob:
        - deploy*.yaml

    - name: generate a private key for vagrant user
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        append: yes
      register: vagrant_user

    - name: deploy vagrant user's public key to git user
      authorized_key:
        user: git
        state: present
        key: "{{ vagrant_user.ssh_public_key }}"
      become: yes

    - name: symlink vaultpw
      file:
        src: "{{ anmad.install_dir }}/test/vaultpassword"
        dest: /home/ansible/.vaultpw
        state: link
        force: true
      become: yes

    - name: ensure anmad is running
      service:
        name: anmad
        state: started
      become: yes

    - name: git test commands
      shell: "git init &&
              git config user.email 'vagrant@example.com' &&
              git config user.name 'Vagrant User' &&
              git add . &&
              git commit -m 'initial commit' &&
              git remote add origin ssh://git@localhost:/srv/git/configmanagement &&
              echo StrictHostKeyChecking no >>~/.ssh/config &&
              git fetch &&
              sleep 10 &&
              git push --set-upstream origin master &&
              git rm ansible/deploy3.yaml &&
              git commit -m 'removed failing playbook deploy3.yaml' &&
              sleep 60 &&
              git push"
      args:
        chdir: /home/vagrant/testdata
        creates: /home/vagrant/testdata/.git
      become: no
      tags: git-test

    - name: git retest commands to enable re-provisioning
      shell: "echo {{ 99999 |random }} > testfile &&
              git add testfile &&
              git commit -m 'random commit {{ 99999 |random }}' &&
              git fetch &&
              git push"
      args:
        chdir: /home/vagrant/testdata
      become: no
      tags: git-test

    - name: pause 150 sec to allow test plays to finish
      pause:
        seconds: 150
